# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvT4k2k07rGOi3vhsoEoxq6YOXzhRsWF
"""

pip install nltk

import nltk
from nltk.tokenize import word_tokenize
import random

# Load the NLTK data needed for tokenization
nltk.download('punkt')

# Define a dictionary of responses for the chatbot
responses = {
    'hello': ['Hi!', 'Hello!', 'Hey!'],
    'goodbye': ['Goodbye!', 'See you later!', 'Farewell!'],
    'thanks': ['You\'re welcome!', 'No problem!', 'Thank you too!'],
    'default': ["I didn't understand that.", 'Can you please rephrase?', 'Sorry, I\'m not sure what you mean.']
}

# Define a function to tokenize user input
def tokenize_input(input_text):
    tokens = word_tokenize(input_text.lower())
    return tokens

# Define a function to generate a response based on user input
def generate_response(tokens):
    for token in tokens:
        if token in responses:
            return random.choice(responses[token])
    return random.choice(responses['default'])

# Create a chatbot interface
def chatbot():
    print('Welcome to the chatbot!')
    while True:
        user_input = input('You: ')
        tokens = tokenize_input(user_input)
        response = generate_response(tokens)
        print('Chatbot:', response)

# Run the chatbot
chatbot()